### ISSUE TITLE
Lgt8fx - ADC analogRead() is wrong - it only returns back 10bit - need to load manually ADCH + ADCL to get 12bit value

### ISSUE THREAD

**Issue by jlsilicon** [dbuezas/lgt8fx#265] opened 2023-04-15 17:34 UTC
I used analogRead() for Lgt8fx , but it only gave me values from 0 to 1023 (10bits).
-- which is wrong for Lgt8f chips.
I needed to manually read ADCH + ADCL to get the values from 0 to 4095 (12bits)

See below : 

    // - wait for ADC Ready 
    // - tests wrong - only 10 bits , input of potentiometer varies between 0 .. 1023
    A_R = analogRead( A0 );  

    // - get true 12bit value - tests correctly - returns 12 bits , input of potentiometer varies between 0 .. 4095
    A_R = ( (ADCH << 8) | (ADCL << 0) );

**Comment by jayzakk** [comment] 2023-04-15 18:04
10 bits is the Arduino default for compatibility reasons.
If you need better (and know your board supports it) you can change with analogReadResolution().

This works as intended, so closing.

Regards,
Oliver

**Closed by jayzakk** 2023-04-15 18:04 UTC

**Comment by jlsilicon** [comment] 2023-04-15 18:13
oh well
