### ISSUE TITLE
WAVGAT Nano Faux clone

### ISSUE THREAD

**Issue by pixelwaster** [dbuezas/lgt8fx#52] opened 2020-09-13 21:40 UTC
Will this info apply to WAVGAT Nano LGT8F boards? They have a 12 MHz resonator which stopped uploading. Now that we can flash a different boot loader, so can I fish this out of the parts bin and use it?

**Comment by dbuezas** [comment] 2020-09-20 14:15
Hello there!
It may work if the problem is the bootloader in the first place. The only complication is that those boards don't have the SWC and SWD pins exposed so you will have to hook directly to the chip.
<img width="587" alt="swd swc" src="https://user-images.githubusercontent.com/777196/93713463-64819b80-fb5c-11ea-8c52-b8b12406847d.png">

**Comment by dbuezas** [comment] 2020-09-20 14:15
Let me know if you succeeded and I'll close the issue :)

**Comment by pixelwaster** [comment] 2020-09-24 07:07
After a but of messing about, removing the resonator, etc; I was able to flash Optiboot. The steetings were LGT8F328 with internal 32 MHz clock with the variant set for QFP32 nano-style.

The SWC and SWD pins are exposed on the six pins opposite the USB, PB5/SCK, Reset, Vcc, and gnd are the rest. Five more pins if I don't need crystal accuracy. I could always use an external ttl osc and go down to 4 pins.

**Closed** 2020-09-24 18:38 UTC
