### ISSUE TITLE
Wrong analogReadResolution on boot

### ISSUE THREAD

**Issue by jayzakk** [dbuezas/lgt8fx#41] opened 2020-08-12 16:34 UTC
As https://www.arduino.cc/en/Reference.AnalogReadResolution states

> It defaults to 10 bits (returns values between 0-1023) for backward compatibility with AVR based boards. 

This doesn't seem to be true - at LGT8F. 
I got values up to 4096, which made my "regular" code not working.

I guess we should change this behaviour.

**Comment by seisfeld** [comment] 2020-08-21 08:39
I can confirm, 12 bit seems to be default. I only see 4064 as max value though, not 4096.

**Comment by dbuezas** [comment] 2020-09-20 14:21
I'm willing to take a PR to start with 10 bits by default :)

**Comment by jayzakk** [comment] 2020-09-20 19:42
Ok, will PR it

**Comment by LaZsolt** [comment] 2020-10-23 14:52
If in wiring_analog.c at line 30 default variables will be set like below, the analogRead() default resolution could be 10 bit.
```
uint8_t analog_resbit = 2;
uint8_t analog_resdir = 1;
```

**Comment by LaZsolt** [comment] 2020-10-23 15:06
@seisfeld 
The gain error correction is the reason of the maximum ADC value is 4064.
```
// gain-error correction
#if defined(__LGT8FX8E__)
	pVal -= (pVal >> 5);
#elif defined(__LGT8FX8P__)
	pVal -= (pVal >> 7);
#endif
```

**Comment by seisfeld** [comment] 2020-10-23 15:08
Good catch @LaZsolt !

**Comment by LaZsolt** [comment] 2020-10-24 11:46
Here is a demonstration program of the ADC gain error. I think the ADC gain error should be mentioned in readme.
```
void setup() {
  Serial.begin(38400);
  
  analogReference(INTERNAL2V048);
  analogReadResolution(12);
  pinMode(DAC0, ANALOG);

  
//------------------------------------------------------
  uint16_t value;

  Serial.print(F("If ADMUX set AGND then ADC output: "));
  value = analogRead(AGND);
  Serial.print(value);  
  Serial.println( (value == 0) ? F("") : F("    ( Must be 0, is'n it? ADC not linear around zero valtage.)"));

  bitSet(ADMUX,4);      // ADMUX switch to DAC output
  printvalueatDAC(0);
  printvalueatDAC(1);
  printvalueatDAC(2);
  printvalueatDAC(3);
  printvalueatDAC(4);
  printvalueatDAC(250);
  printvalueatDAC(251);
  printvalueatDAC(252);
  printvalueatDAC(253);
  printvalueatDAC(254);
  printvalueatDAC(255);
  Serial.println();
  Serial.println(F("The maximum ADC value should be at the maximum DAC output value, but not. The reason is the gain error."));
  Serial.println();
  Serial.println(F("End test."));
  Serial.println();
}// end setup  

void printvalueatDAC(uint8_t x){
  delay(100);
  analogWrite(DAC0, x);
  Serial.print(F("If  DAC  ==  "));
  if (x < 10 ) Serial.print(F(" "));
  if (x < 100) Serial.print(F(" "));
  Serial.print(DALR);
  Serial.print(F("  then ADC output: "));
  Serial.println(directADCread());
}

static uint16_t adcReadNow()
{
  // start the conversion
  bitSet(ADCSRA, ADSC);

  // ADSC is cleared when the conversion finishes
  while (bit_is_set(ADCSRA, ADSC));

  return ADC;
}

int directADCread(){
  uint16_t pVal;
  uint16_t nVal;

#if defined(ADCSRA) && defined(ADCL)
  #if defined(__LGT8FX8P__)
  bitSet(ADCSRC, SPN);
  nVal = adcReadNow();
  bitClear(ADCSRC, SPN);
  #endif
  
  pVal = adcReadNow();

  #if defined(__LGT8FX8P__)
  pVal = (pVal + nVal) >> 1;
  #endif
#else
  // we dont have an ADC, return 0
  pVal = 0;
#endif

  // gain-error correction
#if defined(__LGT8FX8E__)
  pVal -= (pVal >> 5);
#elif defined(__LGT8FX8P__)
  pVal -= (pVal >> 7);
#endif

  return pVal;
}// end directADCread


void loop() {
}
```

**Comment by seisfeld** [comment] 2021-01-26 10:58
@LaZsolt I have a question regarding this gain correction thing. I'm using 2.048V as reference and set the ADC to 12bit. When I want to calculate expected ADC values like:

![Resolution of the ADC](https://user-images.githubusercontent.com/9606362/105836438-74f3c800-5fcd-11eb-9eaf-522738ceb571.png)

What do i use as ADC resolution in that formula? 4096 or 4064?

**Comment by LaZsolt** [comment] 2021-01-26 13:01
The resolution is 4064. Slightly bigger gain decrease the resolution. But replace "System Voltage" to "Reference Voltage".
Voltage Measured = Reference / Resolution * ADC Reading

**Comment by seisfeld** [comment] 2021-01-26 13:06
Thanks. Will take 4064 in all calculations and verify with multimeter. You're right about the ref voltage of course. (The formula image is not mine, I grabbed it off the web just for illustration.)

**Comment by LaZsolt** [comment] 2021-04-02 12:58
@seisfeld  
> Thanks. Will take 4064 in all calculations and verify with multimeter. You're right about the ref voltage of course. (The formula image is not mine, I grabbed it off the web just for illustration.)

As I writed above "Slightly bigger gain decrease the resolution" is true, but in calculations must use 4096.
If the gain error wasn't so big then the ADC value reach the maximum when the input reach the reference voltage.
But becase of error the ADC value reach the maximum **before** the input reach the reference voltage. So the ADC value decreased by gain correction for the good calculation. I hope it is understandable.
```
4096         Reference Voltage
----   =   ---------------------
4063       Max Voltage Mesasured

```

**Comment by LaZsolt** [comment] 2021-04-02 13:15
@jayzakk and @dbuezas: Help wanted? Here it is.

For the backward compatibility of the default analogReadResolution 
I merged this maintenance to my last Pull request. https://github.com/dbuezas/lgt8fx/pull/130

**Comment by dwillmore** [comment] 2023-01-12 19:47
Is this issue also closed by #130 ?

**Comment by dbuezas** [comment] 2023-01-12 20:05
Yes.

**Closed by dbuezas** 2023-01-12 20:05 UTC
Labels: help wanted

**Comment by ariefadha** [comment] 2025-05-13 13:14
Sorry for opening this issue again. Can anyone explain to me why I get max value 4064 in 12 bit ADC instead of 4095?

**Comment by jayzakk** [comment] 2025-05-13 13:30
> Sorry for opening this issue again. Can anyone explain to me why I get max value 4064 in 12 bit ADC instead of 4095?

@LaZsolt already explained here in detail.
Plus, we're talking about a cheap microcontroller, not some expensive lab equipment. The controllers linearity and precision isn't that perfect, too, so why exactly are you missing that single one out of of 4096 values? The lowest and highest couple of values are usually the most unreliable anyways.

Is just, I don't get it.

**Comment by ariefadha** [comment] 2025-05-13 15:42
@jayzakk i am not using this for expensive lab equipment. just for controlling bldc. nor do i care about precision. but lowest value and highest value is mater in some code. it will effect your low and max range in code. instead giving 100% throttle it only give you 98% instead.

what I've read above is because "Slightly bigger gain decrease the resolution" thats why, i need someone to elaborate with this. 

heres why i bothered about 4064 instead 4096 : 

since this is "official" library, (not a random user who made this lib), so I expect to cross microcontrollers behaviour. and of course I can using map(adc,04064,0,4096)
but, once again this is official library, im expecting same result across microcontrollers.

imagine one user made with atmega328 (arduino nano) getting value from 0% to 100%. and another user using lgt8fx, digging hair out wondering why i can only get 98% max throttle.

**Comment by dbuezas** [comment] 2025-05-13 16:07
Note that I am indeed a random user who uploaded something to GitHub and other random (great) guys chimed in to make further improvements.

The only official thing you'll find here is the rule of being polite and thankful that others shared their work for free :)

**Comment by hmeijdam** [comment] 2025-05-13 16:23
> The only official thing you'll find here is the rule of being polite and thankful that others shared their work for free :)

You have just earned yourself the "quote of the week" award.

![Image](https://github.com/user-attachments/assets/a85a10d5-dad8-4ed9-858b-a51f51683d3e)

**Comment by ariefadha** [comment] 2025-05-13 16:48
well can you quote my exact word that I'm indicating not being polite?

1st I post with the word "sorry for opening this issue" (i tot sorry is the most polite way to ask something)

2nd I get answered that not answering my question 
(cheap microcontrollers, not some expensive lab equipment, etc2)

3rd I answer the 2nd comment by point to point for what he mention about.

well im not here to insult someone. and thanks for your hard work and free library.

and for reminder of me, can you please point me what word that im using so you guys feel im not polite. since english is not my language. and I answering according to the 1st reply point @jayzakk

**Comment by dbuezas** [comment] 2025-05-13 17:17
I'll delete all this chitchat (also including your expectations) in a couple of minutes to keep the issue relevant.
Now, although I technically didn't say you weren't polite, I implied I did it. Same way you implied you could give orders like a parent does to a child: "I expect xyz". That's impolite in English. It would be impolite even if you were paying for this, even if you owned it.
You are of course free to say whatever you want, but this won't do much motivating random people to help you. And I may delete it. Cos I can

**Comment by ariefadha** [comment] 2025-05-13 17:41
@dbuezas  well, im sorry if using word "expecting" is form an insult. its because of my vocabulary limitation to pick and choose word. since my original language only has around 120.000words vs english 600.000words. and different regions has difference culture, and yet we can not judge someone by texting. because we can't see the face and intonation/accent.

and i use that just for example and answering. not my point, while my point is asking someone to elaborate, so might i can help and pull. instead forcing my code and ruin the whole library.

in the end i am sorry if i insult @jayzakk and you. i will say no more, thanks for your and others hard works for this library. cheers

i will also delete this comment for a couple minutes. and feel free to delete all my comments as you are the author.

**Comment by dbuezas** [comment] 2025-05-13 18:08
I'll absolutely not delete all the comments! Just removed the offtopic stuff :)

My grain of sand is that normalising analog input would be risky because different boards may have slightly different ranges, and would also affect the output when a different analog reference is used (e.g internal or aref pin).

Also the atmega328p has a 10 bit adc, so it goes to 1024 instead of 4096 as the 12 bit adc in the lgt chip. They are different chips after all.

**Comment by xenos1984** [comment] 2025-08-11 13:06
I am also picking this up, since I have done some measurements to compare the ADC value of a LGT8F328P with the input voltage, measured with a multimeter (actually two multimeters to cross-check, resolution around 0.1mV in the relevant range). To my experience, the gain error here strongly depends on the choice of the reference voltage. For example, for the 1.024V reference it is smaller than for the 2.048V reference, and one would need a different correction factor. Also in the 2.048V case there are quite large steps in the ADC output. The linearity is in general quite good, deviations are less than 5mV, except near the ends of the intervals. I could not test the 4.096V, since the boards I have power the µC at 3.3V, which is too low for that.

With this in mind, I wonder whether the "generic" gain error correction in the Arduino code is actually useful. Surely it corrects *some* case of an observed gain error, but it doesn't seem to offer any benefit if one changes the reference, and the error from non-linearity is actually bigger. If one really wants to have a universally working gain error correction, one would probably have to adapt the code, depending on the chosen reference - and even that most likely depends on the actual board and varies.

Hence, I wonder whether it would actually make sense to remove this correction code, and simply return the raw ADC value, and of course document the actual ADC behavior. If someone really wants to calculate the voltage from the ADC value and cares about the few mV difference, they might be better off writing up their own correction depending on the specific use case, and feed it the raw ADC value instead of "undoing" some correction done by the Arduino code.

(Don't get me wrong, I'm not "missing some values" or "mistaking a cheap device for a high-end one". I'm just questioning the usefulness of the current code and whether it serves its / any actual purpose.)

<img width="841" height="522" alt="Image" src="https://github.com/user-attachments/assets/56d551bb-2724-4d0a-8dd1-d7d264b5cc6d" />
<img width="841" height="522" alt="Image" src="https://github.com/user-attachments/assets/cf85f184-9a59-40bb-878a-4e5f306b4381" />
<img width="841" height="510" alt="Image" src="https://github.com/user-attachments/assets/67b3e86b-9d9b-4dc8-bf38-13d3de3e9529" />
<img width="841" height="510" alt="Image" src="https://github.com/user-attachments/assets/209332e4-4c8d-4988-98a1-2d70906e81f8" />
